drop schema if exists meters;
create schema if not exists meters;
set
initial schema meters;

create table meter_readings
(
    id          bigint primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
    user_id     bigint not null,
    type        varchar(20),
    change_date timestamp,
    value       double
);

create
index user_index on meter_readings(user_id);
create
index type_index on meter_readings(type);